services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-news
      - REDIS_URL=redis://redis:6379  # 🔥 Add this
    depends_on:
      - mongo
      - redis  # 🔥 Add Redis dependency

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:  # 🔥 Add Redis Service
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: